# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf019dd486a51a568927f0f48ead71a6f16b43dccdc4b45e2a47c009ae7359ce8a111b833ec566b6ede4c92e4ad5cd8d558375750afeb24cf4fc81d8859193d6

test:
  secret_key_base: 9a702ec5f91a86552412031858335e42d3d8a11f235cf5e1d7ccfb77e73bcdbebce039501bb82f9a0610ac98dd3acde0ac9caa9bb1c7759af8624e7cae287703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
